### ISSUE TITLE
link preview

### ISSUE THREAD

**Issue by ezazwar1** [nickplesha/ng-cordova-3dtouch#1]
Does Link Preview mean that the webpage link and if so 
then assume i have a ionic tabs project and i am in Chats state and there is a list of profile of ionic people what if i add a link in that div and force touch on that div will it still show me the peek 

I am really confused about Peek and POP how to configure peek as per apple documentation is concerned we can program the peek and show whatever we like

Please clear my doubts

Thanks 
Ezaz

**Comment by nickplesha** [comment]
Hi!

About Link Preview, check this link: https://github.com/EddyVerbruggen/cordova-plugin-3dtouch#enablelinkpreview According to the Cordova plugin documentation it's only for previewing websites and might not be reliable. Try enabling it in your app and report your findings (if you have a 3D touch enabled device since 3D touch is not supported in the emulator right now)-

About customizing the peek: I don't think any Cordova plugins offer support for full customization according to apple documentation, unfortunately. Any custom peek behaviour is done in native code right now. When iOS 10 is released and 3D touch support expands and continues, this is likely to change in the future. 

So I would hold of on trying to implement complex solutions for 3D touch until then. 

The home screen quick actions work really well with Cordova right now if you want to add a minimal level of 3D touch support for iPhone 6S users.

Cheers,
Nikola

**Comment by ezazwar1** [comment]
Thanks @nickplesha
